site_name: Tamesh Docs
site_url: https://3gee.is-a.dev/tamesh-docs/
site_description: Project documentation with Markdown.
site_author: Tamesh

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: edit/main/docs/

theme:
  name: mkdocs
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide/
  - Developer Guide: dev-guide/
  - About:
      - Release Notes: about/release-notes.md
      - Contributing: about/contributing.md
      - License: about/license.md

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search

copyright: Copyright &copy; 2014 MkDocs Team
